import { Controller, Get, Post, Body } from '@nestjs/common';
import { CorrectiveService } from './corrective.service';
import { CorrectiveExercise } from './entities/exercise.entity';

/**
 * REST controller exposing endpoints to retrieve corrective
 * exercises.  This complements the GraphQL resolver by offering a
 * simple JSON-based API for clients that do not consume GraphQL.
 */
@Controller('corrective')
export class CorrectiveController {
  constructor(private readonly correctiveService: CorrectiveService) {}

  /**
   * Return the full list of corrective exercises.  No filtering or
   * pagination is applied.
   */
  @Get('exercises')
  getExercises(): CorrectiveExercise[] {
    return this.correctiveService.findAll();
  }

  /**
   * Create a new corrective exercise entry.  The caller supplies
   * at minimum a title, with an optional description.  A simple
   * incrementing ID is generated by the service.  Returns the
   * created exercise as JSON.
   */
  @Post('exercises')
  createExercise(
    @Body() body: { title: string; description?: string },
  ): CorrectiveExercise {
    return this.correctiveService.create(body);
  }
}